In [31]:
import os
import pandas as pd
import numpy as np

In [10]:
file_path = "datingTestSet2.txt"

In [18]:
def file_to_matrix(file_path):
    df = pd.read_table(file_path, sep='\t', names=['a', 'b', 'c', 'd'])
    dating_matrix = df.ix[:, [0,1,2]]
    category_arry = df.ix[:, 3]
    return dating_matrix, category_arry

In [19]:
dating_matrix, category_arry = file_to_matrix(file_path)

In [20]:
dating_matrix.head()

a          b         c
0  40920   8.326976  0.953952
1  14488   7.153469  1.673904
2  26052   1.441871  0.805124
3  75136  13.147394  0.428964
4  38344   1.669788  0.134296

In [21]:
category_arry.head()

0    3
1    2
2    1
3    1
4    1
Name: d, dtype: int64

In [26]:
set_min = dating_matrix.min(0)

In [27]:
ranges = dating_matrix.max(0) - set_min

In [28]:
norm_data_set = (dating_matrix - ranges) / ranges

In [30]:
type(norm_data_set)

pandas.core.frame.DataFrame

In [34]:
mat_length = norm_data_set.shape[0]
mat_length

1000

In [38]:
ratio = 0.5
using_data_num = int(mat_length * ratio)
using_data_num

500

In [43]:
norm_mat = np.array(norm_data_set)
labels = np.array(category_arry)
testing_data = norm_mat[using_data_num: mat_length]
testing_labels = labels[using_data_num: mat_length]
traing_data = norm_mat[:using_data_num]
traing_labels = norm_mat[:using_data_num]

In [45]:
testing_data[0]

array([-0.69449892, -0.57669275, -0.6631863 ])

In [50]:
single_diff = np.tile(testing_data[0], (traing_data.shape[0], 1)) - traing_data
single_diff

array([[-0.14282427,  0.02525585, -0.22620209],
       [ 0.14676849,  0.08135258, -0.65111272],
       [ 0.02007165,  0.35438201, -0.13836485],
       ...,
       [-0.48671568,  0.0252918 ,  0.00196947],
       [-0.35557065, -0.00588101, -0.51426467],
       [ 0.15977343,  0.15294386, -0.59696546]])

In [56]:
juli = np.sqrt(np.sum(single_diff ** 2, axis=1))
juli[:5]

array([0.26870805, 0.67238903, 0.38096498, 0.56312061, 0.44435388])

In [57]:
sorted_juli = juli.argsort()
sorted_juli[:5]

array([130, 320,  84, 471, 176], dtype=int64)

In [48]:
traing_data_length = traing_data.shape[0]

In [62]:
def classify(single_test_data, traing_data, traing_labels, k):
    diff_mat = np.tile(single_test_data, (traing_data_length, 1)) - traing_data
    distance = np.sqrt(np.sum(diff_mat ** 2, axis=1))
    sortd_distance = distance.argsort()
    
    class_count = dict()
    for i in range(k):
        vote_labels = traing_labels[sortd_distance[i]]
        class_count[vote_labels] = class_count.get(vote_labels, 0) + 1
    sorted_class_count = sorted(class_count.items(), key=lambda item: item[1], reverse=True)
    print(sorted_class_count)
    return sorted[0][0]

In [63]:
outcome = classify(testing_data[0], traing_data, traing_labels, 3)
outcome

TypeError: unhashable type: 'numpy.ndarray'