In [1]:
import pandas as pd

In [2]:
df = pd.read_table('datingTestSet.txt', sep='\t', names=['a', 'b', 'c', 'd'])
df.head()

a          b         c           d
0  40920   8.326976  0.953952  largeDoses
1  14488   7.153469  1.673904  smallDoses
2  26052   1.441871  0.805124   didntLike
3  75136  13.147394  0.428964   didntLike
4  38344   1.669788  0.134296   didntLike

In [3]:
df.ix[:, [0, 1, 2]].head()

a          b         c
0  40920   8.326976  0.953952
1  14488   7.153469  1.673904
2  26052   1.441871  0.805124
3  75136  13.147394  0.428964
4  38344   1.669788  0.134296

In [4]:
category_list = list()

In [5]:
for third_element in df.ix[:, 3]:
    if third_element == 'largeDoses':
        category = 3
    elif third_element == 'smallDoses':
        category = 2
    else:
        category = 1
    category_list.append(category)

In [ ]:
category_list[:6]

In [6]:
def file_to_matrix():
    df = pd.read_table('datingTestSet.txt', sep='\t', names=['a', 'b', 'c', 'd'])
    category_list = list()
    for third_element in df.ix[:, 3]:
        if third_element == 'largeDoses':
            category = 3
        elif third_element == 'smallDoses':
            category = 2
        else:
            category = 1
        category_list.append(category)
    dating_mat_matrix = df.ix[:, [0, 1, 2]]
    return dating_mat_matrix, category_list

In [7]:
dating_mat_matrix, category_list = file_to_matrix()

In [8]:
dating_mat_matrix.head()

a          b         c
0  40920   8.326976  0.953952
1  14488   7.153469  1.673904
2  26052   1.441871  0.805124
3  75136  13.147394  0.428964
4  38344   1.669788  0.134296

In [14]:
category_list[:6]

[3, 2, 1, 1, 1, 1]

In [19]:
import numpy as np
np.random.randint?

In [20]:
df3 = pd.DataFrame(np.random.randint(10, size=(10, 5)), columns=['a', 'b', 'c', 'd', 'e'])
df3

a  b  c  d  e
0  4  9  7  7  9
1  3  6  1  7  0
2  6  1  5  2  2
3  2  0  6  4  2
4  9  0  7  3  2
5  9  2  4  4  6
6  5  8  9  8  6
7  7  3  0  7  7
8  9  0  2  4  1
9  7  9  2  3  4

In [21]:
div = np.array([2,2,2,2,2])
div

array([2, 2, 2, 2, 2])

In [22]:
df3 / div

a    b    c    d    e
0  2.0  4.5  3.5  3.5  4.5
1  1.5  3.0  0.5  3.5  0.0
2  3.0  0.5  2.5  1.0  1.0
3  1.0  0.0  3.0  2.0  1.0
4  4.5  0.0  3.5  1.5  1.0
5  4.5  1.0  2.0  2.0  3.0
6  2.5  4.0  4.5  4.0  3.0
7  3.5  1.5  0.0  3.5  3.5
8  4.5  0.0  1.0  2.0  0.5
9  3.5  4.5  1.0  1.5  2.0

In [23]:
import pandas as pd
from numpy import *

In [24]:

def file_to_matrix(file_path):
    df = pd.read_table('datingTestSet2.txt', sep='\t', names=['a', 'b', 'c', 'd'])
    dating_mat_matrix = df.ix[:, [0, 1, 2]]
    category_array = df.ix[:, 3]
    return dating_mat_matrix, category_array


def auto_norm(data_set):
    set_min = data_set.min(0)
    ranges = data_set.max(0) - set_min
    norm_data_set = (data_set - set_min) / ranges
    return norm_data_set, set_min, ranges

In [54]:
file_path = 'datingTestSet2.txt'
returnMat, classLabelVector = file_to_matrix(file_path)
norm_data_set, set_min, ranges = auto_norm(returnMat)

In [65]:
np.array(classLabelVector)[1:22]

array([2, 1, 1, 1, 1, 3, 3, 1, 3, 1, 1, 2, 1, 1, 1, 1, 1, 2, 3, 2, 1], dtype=int64)

In [62]:
classLabelVector[1:3]

1    2
2    1
Name: d, dtype: int64

In [38]:
norm_data_set.shape

(1000, 3)

In [39]:
norm_data_set.head()

a         b         c
0  0.448325  0.398051  0.562334
1  0.158733  0.341955  0.987244
2  0.285429  0.068925  0.474496
3  0.823201  0.628480  0.252489
4  0.420102  0.079820  0.078578

In [48]:
c = array(norm_data_set)

In [49]:
c

array([[ 0.44832535,  0.39805139,  0.56233353],
       [ 0.15873259,  0.34195467,  0.98724416],
       [ 0.28542943,  0.06892523,  0.47449629],
       ..., 
       [ 0.29115949,  0.50910294,  0.51079493],
       [ 0.52711097,  0.43665451,  0.4290048 ],
       [ 0.47940793,  0.3768091 ,  0.78571804]])

In [52]:
c[2]

array([ 0.28542943,  0.06892523,  0.47449629])

In [53]:
c[1, :]

array([ 0.15873259,  0.34195467,  0.98724416])

In [66]:
ratio = 0.3
mat_len = c.shape[0]
training_data = c[mat_len*ratio:mat_len, :]

D:\software\anaconda\lib\site-packages\ipykernel\__main__.py:3: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  app.launch_new_instance()


In [71]:
diff_mat = np.tile(c[0], (training_data.shape[0], 1)) - training_data

In [73]:
diff_mat[:5]

array([[ 0.38600681,  0.17627293, -0.3632514 ],
       [ 0.04687038,  0.24750608,  0.18548763],
       [ 0.12012315, -0.24283256, -0.40442503],
       [-0.21287785,  0.10795307,  0.04291352],
       [ 0.18802932, -0.05497523,  0.03243111]])

In [76]:
np.sum(diff_mat ** 2, axis=1)

array([ 0.31202499,  0.09786175,  0.23695683,  0.05881242,  0.03942908,
        0.1263512 ,  0.1454731 ,  0.19331218,  0.11267154,  0.28346982,
        0.15529245,  0.07486607,  0.22928558,  0.17766876,  0.45291371,
        0.1950345 ,  0.03953504,  0.29254841,  0.1449671 ,  0.13406492,
        0.06153016,  0.22193355,  0.0155082 ,  0.20564715,  0.20633244,
        0.13746257,  0.19133863,  0.03638077,  0.16505111,  0.18146973,
        0.22261873,  0.30041436,  0.2869055 ,  0.17198288,  0.0129991 ,
        0.30353373,  0.32388379,  0.51096706,  0.35740092,  0.17673933,
        0.20722593,  0.26794962,  0.36325887,  0.12286192,  0.31094697,
        0.31813681,  0.29066106,  0.05038073,  0.16662912,  0.3867335 ,
        0.2085364 ,  0.12846193,  0.18643264,  0.2585528 ,  0.33699329,
        0.20692942,  0.40597841,  0.10648567,  0.1996147 ,  0.41717305,
        0.70002779,  0.14492451,  0.01733333,  0.40652073,  0.16032142,
        0.11223797,  0.07915574,  0.19457651,  0.10588356,  0.37

In [77]:
np.sum?

In [78]:
import math

In [79]:
math.sqrt(4)

2.0

In [80]:
import os

In [92]:
def image_to_vector(file_name):
    line_array = np.zeros((1, 1024))
    with open(file_name) as f:
        contents = f.readlines()
    for line in contents:
        index = contents.index(line)
        for j in range(32):
            line_array[0, 32 * index + j] = int(line[j])
    return line_array

In [93]:
image_to_vector('digits/trainingDigits/0_0.txt')

00000000000001111000000000000000

00000000000011111110000000000000

00000000001111111111000000000000

00000001111111111111100000000000

00000001111111011111100000000000

00000011111110000011110000000000

00000011111110000000111000000000

00000011111110000000111100000000

00000011111110000000011100000000

00000011111110000000011100000000

00000011111100000000011110000000

00000011111100000000001110000000

00000011111100000000001110000000

00000001111110000000000111000000

00000001111110000000000111000000

00000001111110000000000111000000

00000001111110000000000111000000

00000011111110000000001111000000

00000011110110000000001111000000

00000011110000000000011110000000

00000001111000000000001111000000

00000001111000000000011111000000

00000001111000000000111110000000

00000001111000000001111100000000

00000000111000000111111000000000

00000000111100011111110000000000

00000000111111111111110000000000

00000000011111111111110000000000

00000000011111111111100000000000

00000000001111

In [84]:
def img2vector(filename):
    returnVect = zeros((1,1024))
    fr = open(filename)
    for i in range(32):
        lineStr = fr.readline()
        for j in range(32):
            returnVect[0,32*i+j] = int(lineStr[j])
    return returnVect
returnVect = image_to_vector('digits/trainingDigits/0_0.txt')
returnVect

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [86]:
np.sum(line_array - returnVect)

0.0